app:
  name: "URLShortener"
  base_url: "http://localhost:8080"
  port: ":8080"
  env: "dev"


database:
  path_to_db: '/storage'
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "iammiddle"
  dbname: "mydb"
  sslmode: "disable"


logging:
  level: "debug"
  format: "text"